using SpectrumKlinePlayer;
using System.Reflection;
using System.Diagnostics;
using System.IO;
class Verification {
static BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;
static FieldInfo Field(string n)=>typeof(Form1).GetField(n,F)!;
static void Set(Form1 f,string n,object v)=>Field(n).SetValue(f,v);
static void Call(Form1 f,string n,params object?[] args)=>typeof(Form1).GetMethod(n,F)!.Invoke(f,args);
static void Check(bool value,string message){if(!value)throw new Exception(message);Console.WriteLine("PASS "+message);}
[STAThread] static void Main(){
var lines=new TimedLyricLine[]{new(5,"第一句"),new(10,"第二句"),new(10.15,"第三句"),new(60,"重复歌词"),new(90,"尾句")};
Check(LyricPlaybackClock.FindActive(lines,0)==-1,"before first lyric");
Check(LyricPlaybackClock.FindActive(lines,10)==1,"exact timestamp boundary");
var timer=new LyricPlaybackClock();timer.Sample(10,true);Thread.Sleep(200);
Check(timer.Position>10.15&&timer.Position<11,"interpolation continues without another player sample");
double beforeRepeated=timer.Position;timer.Sample(10,true);
Check(timer.Position>=beforeRepeated,"repeated whole-second clock labels do not rewind interpolation");
timer.Sample(50,false);Thread.Sleep(120);Check(timer.Position==50,"paused playback remains still");
timer.Sample(8,false);Check(timer.Position==8,"backward seek aligns immediately");
Check(KugouScreenLyricCapture.TryParseProgress("01:23 / 04:05") is {Position:83,Duration:245},"OCR playback progress parsing");
Check(KugouScreenLyricCapture.TryParseProgress("01:99 / 04:05")==null,"reject invalid OCR seconds");
var stat=BindingFlags.Static|BindingFlags.NonPublic;
void MediaSet(string name,object value)=>typeof(WindowsMediaSessionCapture).GetField(name,stat)!.SetValue(null,value);
MediaSet("estimatedTitle","test");MediaSet("<UsesEstimatedTimeline>k__BackingField",true);
WindowsMediaSessionCapture.ObserveLyric("test",new("同一句",30));MediaSet("estimatedPosition",31.5d);
WindowsMediaSessionCapture.ObserveLyric("test",new("同一句",30));
Check(WindowsMediaSessionCapture.CurrentEstimatedPositionSeconds==31.5,"unchanged OCR line cannot rewind playback clock");
WindowsMediaSessionCapture.ObserveLyric("test",new("下一句",35));
Check(WindowsMediaSessionCapture.CurrentEstimatedPositionSeconds==35,"new observed lyric anchors playback");
WindowsMediaSessionCapture.ObserveLyric("test",new("00:52 / 03:00",52,180,true));
Check(WindowsMediaSessionCapture.CurrentEstimatedPositionSeconds==52,"exact progress corrects a seek");
var lineType=typeof(KugouLocalLyricCapture).GetNestedType("KrcLine",BindingFlags.NonPublic)!;
var lineList=(System.Collections.IList)Activator.CreateInstance(typeof(List<>).MakeGenericType(lineType))!;
lineList.Add(Activator.CreateInstance(lineType,10000,"重复歌词"));lineList.Add(Activator.CreateInstance(lineType,60000,"重复歌词"));
typeof(KugouLocalLyricCapture).GetField("currentLines",stat)!.SetValue(null,lineList);
typeof(KugouLocalLyricCapture).GetField("currentTrackKey",stat)!.SetValue(null,"test");
Check(KugouLocalLyricCapture.TryGetLineStartSeconds("test","重复歌词",61)==60,"repeated chorus chooses nearby occurrence");
var cacheFiles=(List<string>)typeof(KugouLocalLyricCapture).GetField("lyricFiles",stat)!.GetValue(null)!;
cacheFiles.Clear();
typeof(KugouLocalLyricCapture).GetField("nextFileScanUtc",stat)!.SetValue(null,DateTime.UtcNow.AddMinutes(1));
Check(KugouLocalLyricCapture.GetTimeline("retrysong").Length==0,"missing lyric cache does not produce unrelated lines");
string fixture=Path.GetFullPath("Tools/LyricVerification/retrysong.lrc");
File.WriteAllText(fixture,"[00:01.00]下载完成后的歌词\n[00:03.00]第二句\n");
cacheFiles.Add(fixture);
typeof(KugouLocalLyricCapture).GetField("nextTrackRetryUtc",stat)!.SetValue(null,DateTime.MinValue);
Check(KugouLocalLyricCapture.GetTimeline("retrysong").Length==2,"newly available lyric cache reloads without changing song");
using var form=new Form1();typeof(Form1).GetMethods(F).Single(m=>m.Name=="OnFormClosing"&&m.GetParameters().Length==2).Invoke(form,new object?[]{null,new FormClosingEventArgs(CloseReason.None,false)});
Set(form,"closing",false);
Call(form,"ApplyTrackInfo",new MediaTrackInfo("test",120,10,true));Set(form,"lyricTimeline",lines);
Call(form,"UpdateLyrics");Check((string)Field("currentLyric").GetValue(form)! =="第二句","mid-song start selects current lyric");
Thread.Sleep(200);Call(form,"UpdateLyrics");Check((string)Field("currentLyric").GetValue(form)! =="第三句","UI advances while worker provides no new lyric");
Call(form,"ApplyCapturedLyric",new LyricFrame("第二句","00:10","stale worker sample"));Check((string)Field("currentLyric").GetValue(form)! =="第三句","delayed worker sample cannot replace current UI lyric");
Call(form,"ApplyTrackInfo",new MediaTrackInfo("test",120,10,false));Call(form,"UpdateLyrics");Thread.Sleep(200);Call(form,"UpdateLyrics");Check((string)Field("currentLyric").GetValue(form)! =="第二句","pause holds lyric");
Call(form,"ApplyTrackInfo",new MediaTrackInfo("test",120,6,false));Call(form,"UpdateLyrics");Check((string)Field("currentLyric").GetValue(form)! =="第一句"&&((TimedLyricLine[])Field("lyricTimeline").GetValue(form)!).Length==5,"seek preserves full ordered lyric document");
Set(form,"lyricFeedFollow",false);Call(form,"ApplyTrackInfo",new MediaTrackInfo("test",120,95,false));Call(form,"UpdateLyrics");Check(!(bool)Field("lyricFeedFollow").GetValue(form)!,"manual browsing remains until follow is requested");
Call(form,"ApplyTrackInfo",new MediaTrackInfo("next",-1,30,false));Check(((TimedLyricLine[])Field("lyricTimeline").GetValue(form)!).Length==0,"track change clears previous lyrics even without duration");
Set(form,"lyricTimeline",lines);Set(form,"lyricFeedFollow",false);
Call(form,"ApplyTrackInfo",new MediaTrackInfo("next",240,31,false));
Check(((TimedLyricLine[])Field("lyricTimeline").GetValue(form)!).Length==5 && !(bool)Field("lyricFeedFollow").GetValue(form)!,"real duration arriving after track change preserves lyrics and browsing");
var identity=typeof(Form1).GetMethod("MatchTrackIdentity",BindingFlags.Static|BindingFlags.NonPublic)!;
var mismatch=(MediaTrackInfo)identity.Invoke(null,new object?[]{new MediaTrackInfo("previous",300,210,true),"next",true})!;
Check(mismatch.Title=="next"&&mismatch.PositionSeconds<0&&mismatch.DurationSeconds<0,"lagging system metadata cannot lend old clock to new title");
var match=(MediaTrackInfo)identity.Invoke(null,new object?[]{new MediaTrackInfo("next",240,12,false),"next",false})!;
Check(match.PositionSeconds==12&&match.DurationSeconds==240,"matching title retains authoritative progress");
string foreign=Path.GetFullPath("Tools/LyricVerification/unrelated.lrc");File.WriteAllText(foreign,"[00:02.00]重复歌词\n");cacheFiles.Clear();cacheFiles.Add(foreign);
typeof(KugouLocalLyricCapture).GetField("nextFileScanUtc",stat)!.SetValue(null,DateTime.UtcNow.AddMinutes(1));
var liveLookup=typeof(KugouLocalLyricCapture).GetMethod("TryLoadByLiveText",stat)!;
Check(liveLookup.Invoke(null,new object?[]{"重复歌词","next"})==null,"known song never loads another song's matching chorus");
Check(liveLookup.Invoke(null,new object?[]{"重复歌词",null})!=null,"unknown song still supports desktop text cache lookup");
void ClockSet(string name,object? value)=>typeof(KugouPlaybackTimeCapture).GetField(name,stat)!.SetValue(null,value);
ClockSet("pending",new TaskCompletionSource<MediaTrackInfo?>().Task);ClockSet("latest",new MediaTrackInfo("previous",300,210,true));
ClockSet("lastTitle","previous");ClockSet("lastSuccessTick",Stopwatch.GetTimestamp());
var readWatch=Stopwatch.StartNew();var staleClock=KugouPlaybackTimeCapture.TryCapture("next",true);
Check(staleClock==null,"previous track clock cannot leak into next track while lookup is pending");
Check(readWatch.Elapsed.TotalMilliseconds<100,"blocked accessibility lookup does not block metadata polling");
Console.WriteLine("All lyric regression checks passed");
}
}

